# Site settings
title: Nabeel Siddiqui | Assistant Professor of Digital Media 
description: "A minimal, responsive, ready to use blog template, built with Jekyll."
url: "http://nabsiddiqui.github.io"
author:
  name: "Nabeel Siddiqui"
  email: "siddiqui@susqu.edu"
  url: "https://nabsiddiqui.github.io"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-postfiles

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
